# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Accessibility' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'URBNSwiftyConvenience'

  # Pods for Accessibility

  target 'AccessibilityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
